version: '3'
services:
  mysql:
    build: ../images/mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    environment:
     - MYSQL_ROOT_PASSWORD=IOTgroup2$$
    ports:
     - "3306:3306"
  phpmyadmin:
    build: ../images/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=IOTgroup2$$
    ports:
     - "6060:80"
    links:
      - mysql:db
